### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by skichrome** [sylvek/yeelight-arduino#3]
Hello,

I can't compile any sketches because the ide tell me that there is an error with libraries : 

```
/home/toni/Arduino/libraries/yeelight-arduino-master/yeelight.cpp: In member function 'void Yeelight::lookup()':
/home/toni/Arduino/libraries/yeelight-arduino-master/yeelight.cpp:44:8: error: 'class WiFiUDP' has no member named 'beginMulticast'
   _udp.beginMulticast(_ipMulti, 1982);
        ^
/home/toni/Arduino/libraries/yeelight-arduino-master/yeelight.cpp:45:8: error: 'class WiFiUDP' has no member named 'beginMulticastPacket'
   _udp.beginMulticastPacket();
        ^
exit status 1
Erreur de compilation pour la carte NodeMCU 1.0 (ESP-12E Module)
```

My library version is :
WiFi : 1.2.7

Any ideas ? 
Thanks for reply

**Comment by sylvek** [comment]
hello,
this pb seems to come from that you use an ESP8266.
my code is for an ESP32
sadly the udp library is not exactly the same between this 2 devices and you have to change it :-/

https://links2004.github.io/Arduino/d2/d8e/class_wi_fi_u_d_p.html

**Comment by skichrome** [comment]
Ok thank you,
I will use another way to connect to my yeelight bulb, and maybe later I will try to change it.

**Comment by sylvek** [comment]
:+1:
